### ISSUE TITLE
array_merge() - Error if try use custom repeater in static page

### ISSUE THREAD

**Issue by vshepel** [mplodowski/seomanager-plugin-public#10]
Greetings.
I use custom fields in static page, the problem is that I can not add anything due to an error:

![image](https://user-images.githubusercontent.com/14239290/74101732-ae75be00-4b45-11ea-803a-5bab0a20d993.png)

![image](https://user-images.githubusercontent.com/14239290/74101747-e54bd400-4b45-11ea-8a4b-f957d0be39ad.png)

The error occurs only when adding a new element to repeater.

**Comment by mplodowski** [comment]
Please update to version 1.3.2 and check if it works.

**Comment by vshepel** [comment]
Thanks so much for the quick help!
