### ISSUE TITLE
Default canonicals

### ISSUE THREAD

**Issue by ZbyszekRynkiewicz** [mplodowski/seomanager-plugin-public#11]
Hi,

where can I change behaviors of default canonicals? I know I can do it manually (every page), but a setting to chose it would be more appreciated.
By default plugin ads canonical without trailing slash "/" and I would like to setup it the way it ads trailing slash to canonical.

ie.
Now: 
`<link rel="canonical" href="https://example.com/page-1">`
Would love to have this:
`<link rel="canonical" href="https://example.com/page-1/">`

Best regards,
Zbyszek

**Comment by mplodowski** [comment]
Hi,

sorry for late response, I was on holidays.

As I read from some articles it doesn't matter for SEO if you add or not trailing slash, but you have to be consistent.

You can manage this by your own by overriding component partial and add this yourself.

https://octobercms.com/docs/cms/components#overriding-partials

Just change this:

    <link rel="canonical" href="{{ seoTag.canonical_url ?: currentUrl|app }}">

to this:

    <link rel="canonical" href="{{ seoTag.canonical_url ?: currentUrl|app }}/">

**Comment by ZbyszekRynkiewicz** [comment]
Hi,

thank you for a response. I managed to do it, by editing a file within plugin itself.
/plugins/renatio/seomanager/components/seotags/default.htm

I have another problem :)

I can't find a solution to put SEO Manager functionality within Post pages. A creator of a website is not responding to implement it, so I've to try do it myself.

I don't see SEO Manager fields in backend for post (services pages are as posts (type static pages).

Where should I add 
'public $implement = ['@Renatio.SeoManager.Behaviors.SeoModel'];'

so it would be visible in backend posts edits?

**Comment by ZbyszekRynkiewicz** [comment]
I'm trying to implement a plugin within dynamic created content, but with no luck. 

I pasted this code here:

xxxxx87.website.pl/themes/starter/pages/service/content.htm

`==

<?php

function onRun()
{
    
    Event::listen('seo.beforeComponentRender', function ($component, $page) {
        if ($page->url == '/service/:slug') {
            $component->seoTag = $page->controller->vars['service']->seo_tag;
        }
    });
}
`

and nothing happen. Could you please help?

Best regards,
Zbyszek

**Comment by mplodowski** [comment]
> Where should I add
> public $implement = ['@Renatio.SeoManager.Behaviors.SeoModel'];

To implement SEO fields in custom plugin, you must add this code to Post model.
