### ISSUE TITLE
og:image from RainLab blog

### ISSUE THREAD

**Issue by Sforzando87** [mplodowski/seomanager-plugin-public#15]
How do I get the featured image of a blog post to appear on social media using og:image? The plugin says it supports both og:image and RainLab blog - is there a specific piece of code that I need to get the featured blog post image into the header? It is not showing by default.

**Comment by mplodowski** [comment]
Please update to version 1.3.4 and let me know if this fixes the issue for you.

**Comment by mplodowski** [comment]
Edit Post, go to Open Graph tab and there is a Og Image field, where you can choose your image.
