### ISSUE TITLE
Support for OctoberCMS v2

### ISSUE THREAD

**Issue by artistro08** [mplodowski/seomanager-plugin-public#17]
Hey everyone. With the new update of OctoberCMS v2, I was wondering if you guys would support the CMS Extensibility API to integrate the OG Image and the other stuff.

**Comment by brightpixels-design** [comment]
Hi, please update to support v2. 
I am currently exploring OctoberCMS v2 and having just purchased (as I do for all my v1 sites) and installed... it does not seem to function correctly (nor install all the changelog) 

I'd be happy to put $50 towards the work?

**Comment by mplodowski** [comment]
Hi, tomorrow I will have some time to look into this.

**Comment by mplodowski** [comment]
Please update to plugin version 2.0.1 for OctoberCMS v2.

If you are still on OctoberCMS v1 than use version 1.3.4.
