### ISSUE TITLE
Error when updating 1.3.3 -> 1.3.4

### ISSUE THREAD

**Issue by leonaze** [mplodowski/seomanager-plugin-public#18]
Hi, 

Sorry but i'm not really confident with SSH/Composer/... I try to update my october CMS site with your plugin and I always get this error : 

- Root composer.json requires renatio/seomanager-plugin ^1.3, it is found renatio/seomanager-plugin[v1.3.3] in the lock file and renatio/seomanager-plugin[dev-master, v1.1.11] from composer repo (https://gateway.octobercms.com) but these do not match your constraint and are therefore not installable. Make sure you either fix the constraint or avoid updating this package to keep the one from the lock file.

Can you explain me what to do ?

Thanks.

**Comment by leonaze** [comment]
I tried to remove the extension and update October CMS to the latest version and now I can't update from 1.1.11...

**Comment by brightpixels-design** [comment]
@leonaze  I notice the 1.1.11 issue too. 

In the recent OctoberCMS v2.1 update https://octobercms.com/support/article/rn-27 it states that !!! (signifying an important update) are no longer supported as part of the new version file schema. v1.1.11 is the last change/update before the _Important_ update  _**1.2.0  !!! Change event parameters ...**_ 

I don't think the plugin is v2 Compatible yet either.

**Comment by daftspunk** [comment]
Hello @mplodowski 

It looks like you need to tag your latest release in git. There is currently only 1 tag (v1.1.11) and this is what the customers are receiving. We recommend creating a tag for v1.3.4 so the latest version is provided via composer.

Customers, iIn the meantime, you can target the `dev-develop` branch in composer to get the latest codebase.

Thanks!

**Comment by mplodowski** [comment]
Please update to plugin version 2.0.1 for OctoberCMS v2.

If you are still on OctoberCMS v1 than use version 1.3.4.
