### ISSUE TITLE
Website error after update

### ISSUE THREAD

**Issue by mjafartp** [mplodowski/seomanager-plugin-public#19]
I am using October 1.x just updated October after that website stopped working. 

error `Class 'October\Rain\Support\Facades\Event' not found `

how to go back to the old version?

**Comment by mplodowski** [comment]
The last version which supports October 1.x is 1.3.4.

I recommend you to disable updates for this plugin until you upgrade to October 2.x

Here is zip file, so you can revert your changes.

[seomanager-plugin-1.3.4.zip](https://github.com/mplodowski/seomanager-plugin-public/files/7196968/seomanager-plugin-1.3.4.zip)
