### ISSUE TITLE
getting error after update plugin

### ISSUE THREAD

**Issue by frasjaf** [mplodowski/seomanager-plugin-public#20]
i have october cms v-1 i updated the plugins and got this error
Symfony\Component\Debug\Exception\FatalThrowableError: 
Class 'October\Rain\Support\Facades\Event' not found 
in /var/www/vhosts/soske.me/suma.soske.me/plugins/renatio/seomanager/classes/SeoCmsPage.php:21

**Comment by mplodowski** [comment]
Please read this issue https://github.com/mplodowski/seomanager-plugin-public/issues/19.
