### ISSUE TITLE
how to upgrade to 3.1.0

### ISSUE THREAD

**Issue by sppet** [mplodowski/seomanager-plugin-public#23]
Hello,

I am using v3.0.1, how can I upgrade to v3.1.0?

Thanks

**Comment by mplodowski** [comment]
Command `php artisan october:update` in project root should also update plugins. If this will not update seomanager plugin then try `php artisan project:sync`

Then you should run `php artisan october:migrate` to run migrations.

**Comment by sppet** [comment]
thanks `php artisan october:update` worked
