### ISSUE TITLE
Meta description limit change

### ISSUE THREAD

**Issue by adrian-stein** [mplodowski/seomanager-plugin-public#29]
Hi there,

We use your plugin on all our sites but have noticed that the meta description limit is set to 300. Google has since changed the limit to be 150-160 as seen here: https://blog.bit.ai/meta-description-length/. Any chance you can update this or make the limit configurable via a setting or something? I can change the lang file but the countdown and hard limits on save are hard coded. I am using it with October 2 currently.

Thank,
Adrian

**Comment by mplodowski** [comment]
Changed in v5.0.5
