### ISSUE TITLE
Problem with models not implementing ExtendableTrait and HasRelationships

### ISSUE THREAD

**Issue by kiselli** [mplodowski/seomanager-plugin-public#3]
We expected the problem with RainLab.Sitemap, but this Problem may occur on other Plugins too.

The problem root cause is the SeoModel expects all widget models to implement ExtendableTrait and HasRelationships but there is no check the model does. So when you try to render a Backend Form with Renatio.SeoManager enabled it fails!

The Problem can be found in Renatio\SeoManager\Behaviors\SeoModel line 59 `if (isset($widget->model) && $widget->model->isClassExtendedWith(static::class)) {`

There should be a Check for Traits used or if model is extending Model class.

**Comment by kiselli** [comment]
Sure,

Steps to reproduce:
1. Install Renatio.SeoManager
2. Install RainLab.Sitemap
3. Create a CMS Page e.g. News with "blogPost" Component and URL eg. /news/:slug
4. Go to Settings > Sitemap
5. Add Follogin Item: Type: Blog article, Reference: First Blog post, CMS Page: News
6. Save Sitemap
7. Reload Settings > Sitemap

An Exception will be thrown
 
Example Code for News Page (news.htm):

```
title = "News"
url = "/news/:slug"
is_hidden = 0

[blogPost]
slug = "{{ :slug }}"
==
{% component 'blogPost' %}
```

**Comment by mplodowski** [comment]
Please upgrade to version 1.2.1 and check again.

**Comment by kiselli** [comment]
Works like a charm!
