### ISSUE TITLE
Strip tags from default meta description values

### ISSUE THREAD

**Issue by thedoofus** [mplodowski/seomanager-plugin-public#30]
**Is your feature request related to a problem? Please describe.**
For our clients we use the richeditor for blog posts rather than the markdown editor. If the seo meta description is empty, It's default values are taken from the content of the post. Because we use the richeditor, it includes the html tags.

**Describe the solution you'd like**
It would be great if strip_tags() could be used on the default value for meta description.

**Describe alternatives you've considered**
At the minute, I'm extending the Post model to remove strip tags myself which is fine. Just making a suggestion for when I use this plugin again in the future.

**Comment by mplodowski** [comment]
Added in v5.0.5
