### ISSUE TITLE
Class "Facades\Renatio\SeoManager\Classes\SeoFields" not found

### ISSUE THREAD

**Issue by panki3a** [mplodowski/seomanager-plugin-public#32]
**Describe the bug**
Class "Facades\Renatio\SeoManager\Classes\SeoFields" not found

There is brouken import for class SeoFields

**Screenshots**
<img width="920" alt="image" src="https://github.com/mplodowski/seomanager-plugin-public/assets/16493179/5b4c0628-69e3-478a-96f1-5e87197a01ba">

**October version**
3.4.14

**Plugin version**
"renatio/seomanager-plugin": "^5.0.4",

**Additional context**

**Comment by mplodowski** [comment]
I am using real time facades here. The code is working, so the issue is just your IDE false report.

https://laravel.com/docs/10.x/facades#real-time-facades
