### ISSUE TITLE
Tags for pages in multisite mode

### ISSUE THREAD

**Issue by get-web** [mplodowski/seomanager-plugin-public#34]
How to apply SEO for pages in multisite mode. So that each site has its own tags? 
For example, the page home.htm Currently, the same description applies to all sites.

**Comment by mplodowski** [comment]
Hi,

if you have multiple sites with different locale, than the best solution right now is to use Translatable Plugin. Then in backend editor for CMS page there will be new tab "Translate SEO". You can there translate SEO tags for each locale.

https://octobercms.com/plugin/rainlab-translate

If you have multiple sites, but some have the same locale, than I would try to handle this by using child theme for each site. In site config you can point site to the child theme.

I hope this helps.

**Comment by get-web** [comment]
I was hoping it would be possible without rainlab-translate, but okay. Thanks
