### ISSUE TITLE
*solved* error when adding seo manager to october fresh

### ISSUE THREAD

**Issue by kff5000** [mplodowski/seomanager-plugin-public#5]
*solved*: php artisan plugin:refresh Renatio.SeoManager fixed it

Hi Renatio,

I just bought SEO manager and added it to an october project (fresh install Build 443). When updating the october installation via backend I get the following error (even if I select "skip once" as action): 

`"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'kcb7_october.renatio_seomanager_seo_tags' doesn't exist (SQL: select * from `renatio_seomanager_seo_tags` where `renatio_seomanager_seo_tags`.`seo_tag_id` = 9 and `renatio_seomanager_seo_tags`.`seo_tag_id` is not null and `renatio_seomanager_seo_tags`.`seo_tag_type` = RainLab\Blog\Models\Post limit 1)" on line 664 of /var/www/virtual/kcb7/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php`

Can you help?
Chris (newbie on GitHub and in general)

**Comment by mplodowski** [comment]
Hi Chris,

I don't know why, but October does not run plugin database migration. Maybe some internal error in your project.

I'm glad you solved this.
