### ISSUE TITLE
Support translation SEO Fields in RainLab.Blog

### ISSUE THREAD

**Issue by charles-tainui** [mplodowski/seomanager-plugin-public#6]
hello,

Rainlab.Translate installed.

Wereas everything works greats for pages, languages dropdown menus do NOT appear  into SEO tag for blog posts … any idea ?

Regards

**Comment by mplodowski** [comment]
Hi,

sorry for late response.

I am using polymorphic relation to setup SEO Fields for October Models, but this is not working with RainLab.Translate plugin yet.

I will try to handle this issue soon.

**Comment by marcomessa** [comment]
Hello, any news on this issue?

**Comment by impactfactory** [comment]
It's a very important feature as in some countries, especially Europe, every website has to multilanguage. Plugins without translations cannot be used then. Does it need a donation so we receive this? :)

**Comment by mplodowski** [comment]
It took me some time, but this feature is finally available with version 3.0.0. This version only supports OctoberCMS 2.x, so please upgrade your October installation before upgrading SeoManager plugin.

OctoberCMS and RainLab.Translate does not fully support polymorphic relation for models.

To solve this problem and make integration with other models available you must add columns to model database table. There is new console command that will scan for all models that implement SeoModel behavior and migrate database tables to add required columns.

```
php artisan seo:migrate-tables
```

There is also new command that will migrate old data from `renatio_seomanager_seo_tags` to models that implement SeoModel behavior.

```
php artisan seo:patch 3.0
```
