### ISSUE TITLE
Potential bug

### ISSUE THREAD

**Issue by kombimedia** [mplodowski/seomanager-plugin-public#7]
Awesome plugin! However, when I collapse the component to reveal the html markup, the plugin no longer works i.e. the component variables don't pull through any SEO data.

Any ideas on how to fix this?

I am running SEO Manager version 1.2.2 and October build 454.

Cheers,

**Comment by kombimedia** [comment]
Hi there,

Given that this is a paid plugin I was hoping that you would offer support and respond to issues.. Are you still maintaining this plugin?

Cheers,

**Comment by mplodowski** [comment]
Hi,

sorry for late response.

I am using component `onRender` method to setup SEO fields. When you reveal component markup like that, this method will not run and SEO fields will not be set.

If you want to override component markup, than you should do this like that:

https://octobercms.com/docs/cms/components#overriding-partials

**Comment by kombimedia** [comment]
Hi @mplodowski ,

Cool. Yeh I sorted this and overrode the component partials as you suggest.

Cheers
