### ISSUE TITLE
Link policy ignored in currentUrl

### ISSUE THREAD

**Issue by petehalverson** [mplodowski/seomanager-plugin-public#8]
Fix for honoring the CMS link policy:

Set currentUrl to path (plugins/renatio/seomanager/components/SeoTags.php)

```
$this->page['currentUrl'] = request()->path();
```

Use twig app filter in component markup (plugins/renatio/seomanager/components/seotags/default.htm):
```
<link rel="canonical" href="{{ seoTag.canonical_url ?: currentUrl|app }}">
...
<meta property="og:url" content="{{ currentUrl|app }}">
```

**Comment by mplodowski** [comment]
Thanks! It will fixed in next build.
