### ISSUE TITLE
Ability to edit CMS SEO without CMS permissions

### ISSUE THREAD

**Issue by artistro08** [mplodowski/seomanager-plugin-public#9]
I would love to have a way to edit the SEO without giving my clients access to the CMS pages required. A lot of work that I do requires a custom coded template and this would be an awesome thing to have on hand

**Comment by mplodowski** [comment]
Currently this plugin extends CMS Page and adds SEO fields, so access to CMS Page is required.

The only solution would be create management of SEO Fields outside CMS Page, but I don't like this approach.

I can recommend you to create custom plugin, that will remove CMS Page fields, based on user permissions.
